backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: paulhayes/girl_hours_and_horse_powers
media_folder: static/img
public_folder: /img
editor:
  preview: false
i18n:
  structure: multiple_files
  locales: [en, pt, sv]
  default_locale: en
collections:
  - name: 'pages'
    label: 'Pages'
    slug: '{{slug}}'
    files:
      - label: "power"
        name: "Power"
        file: "content/power/index.en.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: "About"
        file: "content/about/index.en.md"
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    # i18n: true
    create: true
    slug: '{{slug}}'
    path: '{{slug}}/index.en'
    # media_folder: ''
    # public_folder: ''

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }